"""empty message

Revision ID: 3e88df923a8a
Revises: c12393579a33
Create Date: 2020-01-20 17:45:12.165680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e88df923a8a'
down_revision = 'c12393579a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Open'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
