"""empty message

Revision ID: 54beacd50b8b
Revises: 4982163548c9
Create Date: 2019-12-04 10:32:38.462275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54beacd50b8b'
down_revision = '4982163548c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
