"""empty message

Revision ID: abb881b3a936
Revises: 64d295658bc1
Create Date: 2019-12-02 14:59:24.386248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb881b3a936'
down_revision = '64d295658bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###
