"""empty message

Revision ID: db23b98144b2
Revises: 12a11936a10f
Create Date: 2019-12-09 13:42:40.602802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db23b98144b2'
down_revision = '12a11936a10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'user', ['assigned_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_id')
    # ### end Alembic commands ###
